version: '3'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    labels:
      SERVICE_ADDRESS: 172.0.0.1
      SERVICE_TAGS: postgres
      SERVICE_NAME: postgres
      SERVICE_ID: postgres
    ports:
      - "5432:5432"
    networks:
      - local_default
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

networks:
  local_default:
    external:
      name: local_default

volumes:
  postgres_data:
    driver: local
